### ISSUE TITLE
CSS 设计模式

### ISSUE THREAD

**Issue by laclys** [laclys/Front-End_practice#81]
### OOCSS

OO：面向对象

原则一：容器与内容分离
原则二：结构与皮肤分离
原则三：面向设计开发

应用：Grid栅格系统

### BEM

块(Block)、 元素(Element)、修饰符(Modifier)

作用：命名规范、让页面结构更清晰
进阶版oocss

### SMACSS
分类：Base、Layout、 Modules、State、Theme
好处：易维护、易复用、易扩展。。
命名规范：.l-header .is-hidden .theme-nav

### ACSS
一个样式属性一个类
好处：极强的复用性、维护成本低
坏处：破坏了CSS命名语义化

**Comment by laclys** [comment]
```css
img {
  width: 100%;
  vertical-align: middle;
}
```
去除图片默认间隙
